### ISSUE TITLE
f90nml.read() crashes for namelists without a terminating EOL.

### ISSUE THREAD

**Issue by neutrinoceros** [marshallward/f90nml#64] opened 2018-01-21 13:16 UTC
I'm trying to transform a list of configuration files into a list of f90nml.Namelist objects.
StopIteration is being raised by Tokenizer.update_chars().

For example, let's say I have two nml files, foo.nml and bar.nml, this bug can be triggered by : 
```python
[f90nml.read(s) for s in ['foo.nml','bar.nml']]
```

**Comment by marshallward** [comment] 2018-01-21 20:26
Your example is working for me.  There may be a problem with your specific namelists.  Could you include them here?

**Comment by neutrinoceros** [comment] 2018-01-21 22:47
In fact I was able to reproduce this and even more worrisome bugs with extremely simple namelists.
here's my test script (run with pytest)

```python
import f90nml

confs = ['conf1.nml', 'conf2.nml']

def test_minimal():
    a = f90nml.read('conf1.nml')

def test_getitem():
    a = f90nml.read(confs[0])

def test_comprehension():
    b = [f90nml.read(s) for s in confs]
```
my namelists files contain 
```
&dummy
  paramh = 1
  paramg = 2
/
```
and
```
&Dummylist2
  param1 = 3
  param2 = 4
/
```
And here are my results:
[pytest.log](https://github.com/marshallward/f90nml/files/1650296/pytest.log)

It seems that even the simplest test doesn't run, which makes me suspicious about the environment, but I have no clue. Was your package tested on python3.6 yet ?

**Comment by marshallward** [comment] 2018-01-21 23:00
The script is working fine for me (in both 2.7 and 3.6), but I don't use pytest, so I wonder if has something to do with that.

Also it may be that your f90nml is out of date?  Can you check your version?  Is it the latest?

I haven't used pytest before but I'll try to see if I can reproduce this issue.

**Comment by marshallward** [comment] 2018-01-21 23:02
Actually, looking at your logs, I'd be more inclined to point the finger at anaconda (which I also don't use, unfortunately) so that is also work looking over.

It's also possible that there are some non-ASCII characters in here that are tripping up the module.  Is there any way to attach the namelist files here?

**Comment by neutrinoceros** [comment] 2018-01-21 23:06
Actually I'm using pytest because I assumed it was commonly used, but I get the same results through a simple python interpreter.

It's entirely possible that Anaconda could be faulty...
Here are my namelists files (renamed '.log' so I could attach them :) )
[conf1.log](https://github.com/marshallward/f90nml/files/1650329/conf1.log)
[conf2.log](https://github.com/marshallward/f90nml/files/1650330/conf2.log)

**Comment by neutrinoceros** [comment] 2018-01-21 23:08
Could reproduce the issue on another machine, that's also using anaconda3.6.

**Comment by marshallward** [comment] 2018-01-21 23:11
OK, I can reproduce this now.  Your files do not end with `\n` (Unix convention, but not elsewhere).  I do rely a lot on `\n` in the tokenizer to complete the tokenization of the line.

Thanks for reporting this, I miss a lot of these problems living in the Unix bubble.  I will try to fix this soon.

**Comment by marshallward** [comment] 2018-01-21 23:22
I've merged a fix into master, we now send a `\n` upon `StopIteration`, which should be safe since we aggressively check for `\n` to terminate iteration outside of next.

Thanks for spotting and reporting this, let me know how you go with it.

**Comment by neutrinoceros** [comment] 2018-01-22 06:31
Thank you very much for this patch.
However, I'm not sure how I should update your package (using pip): I get as far as version 0.23 but that's it. I guess I can clone the repo too but maybe there's a better way ?

FYI, I'm also living in the UNIX bubble, but apparently it never occured to me to check if I ended my files with a '\n' :-) 
I'll wait on your answer to reinstall this package and I'll report the results once I got it.

**Comment by marshallward** [comment] 2018-01-22 09:58
normally I'd push it onto pypi, but I have been preparing for a 1.0 release and am waiting on some feedback before making the final release.

But I reckon it will be soon, in the next couple of days.  If it gets any longer then I'll just push another pre-release.

**Comment by neutrinoceros** [comment] 2018-01-22 10:56
Ok It's perfectly fine for me. In the meantime I'll just be extra cautious with EOL in my files.
I'll come back in a week tops. Keep up the good work and thanks for your quick answers !

**Comment by marshallward** [comment] 2018-01-23 02:35
Great, I will close this issue for now.

**Closed by marshallward** 2018-01-23 02:35 UTC

**Comment by neutrinoceros** [comment] 2018-01-31 09:00
Just as a feedback : I upgraded to f90nm 1.0.2 and the bug I reported is correctly fixed.
Thanks again !

**Comment by marshallward** [comment] 2018-01-31 11:06
Great, glad to hear :)
