### ISSUE TITLE
Cannot parse a namelist without the right boundary of the array

### ISSUE THREAD

**Issue by coreur** [marshallward/f90nml#129] opened 2021-04-28 11:58 UTC
I have a namelist like this ( `q` is an eight dimensional array, `q(8)` ) :
```fortran
&example
q(1) = 1, 2, 3
q(4) = 4, 5, 6
/
```
Fortan can parse correctly and get `q = 1, 2, 3, 4, 5, 6`, but f90nml cannot parse correctly: `Namelist([('example', Namelist([('q', [1, None, None, 4])]))])`

**Comment by marshallward** [comment] 2021-04-28 13:32
I can reproduce this in gfortran 10.2 and ifort 19.1.

I'm unsure if it is standards-conformant, since it often says things like "the number of values following the equals shall not exceed the number of list items in the expanded sequence".  What's not clear to me is if something like `q(4)` is a scalar or a four-element array.

But I am aware that most compilers will do as you describe and treat variables as de facto pointers, regardless of what the standard may say.

I may be able to alter the index iterators to always run indefinitely, and arbitrarily pad out the arrays as needed.  It's not clear to me if this is what people would want, though.

The "best" solution would be to explicitly declare the designators as arrays:
```
&example
q(1:) = 1, 2, 3
q(4:) = 4, 5, 6
/
```
but perhaps some solution can be found here.

**Comment by marshallward** [comment] 2021-04-28 14:14
Dropping the end index test inside `FIndex` was more effective that I had expected, but not perfect.  The following tests caused hangs:
* test_empty_grp_no_end
* test_string_grp_no_end
* test_file_grp_no_end 
* test_findex_iteration

The first three attempt to provide some better handling when the end token (usually `/`) is missing.  The fourth is more of a unit test for FIndex, the array index iterator.

None of these failures seem serious to me, so it may be possible to implement your suggestion.

**Comment by marshallward** [comment] 2021-04-28 14:20
This is not directly related to the question, but I note that the following case fails:
```
&example
q(1:2) = 1, 2, 3
q(4:5) = 4, 5, 6
/
```

GFortran gives this error:
```
forrtl: severe (18): too many values for NAMELIST variable, unit 100, file /home/marshall/test/nml/q.nml, line 3, position 0
```

My guess is f90nml would (incorrectly?) produce something like `[1, 2, None, 4, 5]`.

In any case, it seems that there is still value in tracking the end index.  But there does seem to be something a bit confusing or special about the handling of an array element.

**Comment by marshallward** [comment] 2021-04-28 15:27
I am having trouble resolving this case:
```
&test_nml
    v(1, :) = 1, 2, 3
/
```
Currently, if `i_end` is unset, then I explicitly set it to `i_start + 1`.  This is mainly to map the Fortran slice onto an equivalent Python slice.

I am testing if it is safe to interpret `v(1)` as `v(1:)` without ambiguity.  Often it works without an issue: We can iterate over the values and stop when we run out of values.  We can extend and reshape `v` after each iteration.

However, one of the main purposes of `FIndex` is to map the serialized list of values to the appropriate elements of amultidimensional array.

If I try to interpret `v(1, :)` as `v(1:, :)` then there is no way to determine when it is time to iterate the second dimension; I just indefinitely increase the first index.

More generally, we're giving up the ability to distinguish `v(1)` and `v(1:)` when tracking and storing the index.

I have not completely given up here.  For example, it may be adequate to check if we are in the final axis.  But this may be one of those cases where f90nml cannot resolve without access to the source code.

**Comment by coreur** [comment] 2021-04-30 13:19
After reading your answer, I find it difficult to correctly distinguish whether `q(4)` is an element of an array or an array without the source code. So, it may be a better solution to add an end index for the arrays to process these namelists. 
I did not consider this problem in all its aspects. Thank you for your reply.

**Comment by coreur** [comment] 2021-05-01 08:11
Can f90nml parse the namelist from the string?
I formatted the string read from the file to meet the namelist standard. I want to parse the namelist directly from the processed string, but it seems that f90nml can only parse namelist from the file. Although it is easy to write a temporary file, it would be better if namelist can be parsed directly from the string.

**Comment by marshallward** [comment] 2021-05-01 13:06
Could you post an example?  I'm not sure what you are trying to do.

There is `f90nml.reads(s)` if you want to parse a string.

**Comment by marshallward** [comment] 2021-05-01 13:09
Sorry, let me clarify.  The parser has a `reads` function, not the top-level module.  Something like this:
```
import f90nml
parser = f90nml.Parser()
nml = parser.reads('&test_nml x = 1 /')
```
If it's not in the model-level API then we could add it without much trouble.

**Comment by coreur** [comment] 2021-05-02 03:40
`Parser().reads()` works well in most cases, but in some cases it will report errors. If there is only one `*` in a line, the parser cannot parse the string correctly.

**test.nml**  
```fortran
*Test1: *
Test2: no *
/Test4: /
!Test5: only one * in line
*
&example1
x = 1
y = 2
/
&example2
q(1:) = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
q(11:) = 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
/
```
test_read_string.py
```python  
import f90nml
parser = f90nml.Parser()
with open('test.nml', "r", encoding="utf-8") as fnml:
    content = fnml.read()
nml = parser.reads(content)
print(nml)
```

**Comment by marshallward** [comment] 2021-05-02 14:29
I'm also seeing a problem with this case.  I have this error:
```
Traceback (most recent call last):
  File "<..>/f90nml/dev.py", line 5, in <module>
    nml = parser.reads(content)
  File "<..>/f90nml/f90nml/parser.py", line 300, in reads
    return self._readstream(iter(nml_string.splitlines()))
  File "<..>/f90nml/parser.py", line 355, in _readstream
    self._update_tokens()
  File "<..>/f90nml/parser.py", line 781, in _update_tokens
    while next_token[0] in self.comment_tokens + whitespace:
IndexError: string index out of range
```

The tokenizer output is odd, anything outside of the namelist groups is bundled as a single token per line, and in nearly every case it drops the final character.
```
['*Test1: ']
['Test2: no ']
['/Test4: ']
['!Test5: only one * in lin']
['']
['&', 'example1']
['x', ' ', '=', ' ', '1']
['y', ' ', '=', ' ', '2']
['/']
! etc...
```
I have to admit that I've not paid much attention to handling content outside of the groups, so I will need to have a look at what's going on here.

**Comment by marshallward** [comment] 2021-05-02 17:57
Looks like it was just a bug, and I didn't use `splitlines()` properly.  Adding the `keepends` argument seems to work:
```
diff --git a/f90nml/parser.py b/f90nml/parser.py
index 971ad4e..8b71bae 100644
--- a/f90nml/parser.py
+++ b/f90nml/parser.py
@@ -297,7 +297,7 @@ class Parser(object):
         >>> data_nml = parser.reads('&data_nml x=1 y=2 /')
         """
         try:
-            return self._readstream(iter(nml_string.splitlines()))
+            return self._readstream(iter(nml_string.splitlines(keepends=True)))
         except StopIteration:
             raise ValueError('End-of-file reached before end of namelist.')
```
I will push this change.

**Comment by marshallward** [comment] 2021-05-02 18:01
Can you test the latest push? a94f45338ccc4e6208a6447b4063fd4b33e43000

**Comment by marshallward** [comment] 2021-05-02 18:16
There was a Python 2 issue, fixed in dc5a70bcceb43e9b6afe1f8f33487b17e9a176e0.

**Comment by coreur** [comment] 2021-05-05 07:31
> Can you test the latest push? [a94f453](https://github.com/marshallward/f90nml/commit/a94f45338ccc4e6208a6447b4063fd4b33e43000)

In my running environment, it runs successfully without problems.

**Comment by chhlab** [comment] 2021-06-13 14:45
I have a namelist file lilke this:
```
$config_nml
x(1:) = 0.54,0.83,1.03,1.10,1.14,1.14,1.12,1.11,1.10,1.08,1.07,
        1.06,1.06,1.06,1.05,1.05,1.06,1.07,1.07,1.07,1.06,1.00,0.93,0.73,0.46,
y(1:) = 0,0.75,1.25,1.75,2.25,2.75,3.25,3.75,4.25,4.75,5.25,5.75,
        6.25,6.75,7.25,7.75,8.25,8.75,9.25,9.75,10.25,10.75,11.25,11.75,12.5,
x(26:) = 0.58,0.86,1.02,1.06,1.09,1.10,1.09,1.09,1.09,
         1.08,1.08,1.07,1.07,1.07,1.07,1.06,1.06,1.06,1.06,1.05,1.04,
         1.00,0.95,0.87,0.52,
y(26:) = 0,0.75,1.25,1.75,2.25,2.75,3.25,3.75,4.25,4.75,5.25,5.75,
         6.25,6.75,7.25,7.75,8.25,8.75,9.25,9.75,10.25,10.75,11.25,11.75,12.5,
x(51:) = 0.63,0.90,1.04,1.07,1.09,1.08,1.07,1.07,1.06,
         1.05,1.04,1.04,1.04,1.04,1.03,1.04,1.04,1.04,1.05,1.05,1.04,
         1.02,0.97,0.83,0.56,
y(51:) = 0,0.75,1.25,1.75,2.25,2.75,3.25,3.75,4.25,4.75,5.25,5.75,
         6.25,6.75,7.25,7.75,8.25,8.75,9.25,9.75,10.25,10.75,11.25,11.75,12.5,
x(76:) = 0.61,0.81,0.95,1.02,1.06,1.07,1.06,1.06,1.06,
         1.05,1.06,1.06,1.06,1.07,1.08,1.08,1.10,1.11,1.13,1.12,1.07,
         0.99,0.84,0.61,
y(76:) = 0,0.52,0.83,1.16,1.65,2.28,2.87,3.50,4.15,
         4.78,5.37,6.00,6.65,7.28,7.87,8.50,9.15,9.78,10.37,11.00,11.82,12.13,12.5,
x(100:) = 0.69,0.82,0.94,1.00,1.03,1.04,1.04,1.04,1.04,
         1.05,1.05,1.05,1.05,1.06,1.06,1.07,1.08,1.09,1.09,1.09,1.06,1.01,0.88,0.75,
y(100:) = 0,0.52,0.83,1.16,1.65,2.28,2.87,3.50,4.15,
         4.78,5.37,6.00,6.65,7.28,7.87,8.50,9.15,9.78,10.37,11.00,11.82,12.13,12.5,
/
```
When I use f90nml to parse the file, there will be an extra empty value. I don't know what caused the empty value. 
Here is my code:
```
import f90nml
with open('sample.nml', "r", encoding="utf-8") as fr:
    nml = f90nml.read(fr)
    print(nml)
```

![result](https://user-images.githubusercontent.com/48938342/121811990-cb218900-cc98-11eb-9bd9-140e3982de1e.png)

![nml file](https://user-images.githubusercontent.com/48938342/121812002-d1176a00-cc98-11eb-979d-43f68c4c08b7.png)

**Comment by marshallward** [comment] 2021-06-13 16:30
I count 23 values in `y(76:)`, filling elemenst from 76 to 76+23-1=98.  Element 99 is unfilled.

You then start filling from `y(100:)` onward.

Is this not correct?

(Also, this probably belongs in a separate issue, especially since the current one is still unresolved.)

**Comment by chhlab** [comment] 2021-06-14 00:53
I got it. Thank you. I will check the namelist file.
I'm sorry I don't know much about github issue. I will delete my previous comment and this one later, so as not to confuse others.

**Comment by marshallward** [comment] 2021-06-14 01:09
No worries, always better to ask than to not ask.

**Closed** 2023-03-22 14:01 UTC
