### ISSUE TITLE
f90nml.patch: overwriting a longer array produces inconsistent results

### ISSUE THREAD

**Issue by jpli** [marshallward/f90nml#38] opened 2016-09-15 11:58 UTC
#35 reminds me of something confusing about f90nml.patch. Overwriting a longer array does not result in a completely new array in the target namelist, trailing items remain after the leading corresponding items have been replaced, which is inconsistent with the object returned by the patch function.

    >>> f90nml.read('test1.nml')
    Namelist([('seq', Namelist([('fib', [1, 1, 2, 3, 5])]))])
    >>> f90nml.patch('test1.nml', {'seq': {'fib': [1, 2, 3, 5]}}, 'test2.nml')
    Namelist([('seq', Namelist([('fib', [1, 2, 3, 5])]))])
    >>> f90nml.read('test2.nml')
    Namelist([('seq', Namelist([('fib', [1, 2, 3, 5, 5])]))])
    >>> print open('test2.nml').read()
    &seq
      fib = 1, 2, 3, 5, 5
    /

In the target namelist, the array is modified rather than added new copies, so I assume it's a different issue from #35.

**Comment by marshallward** [comment] 2016-09-15 20:26
I see, it overwrites the original array elements rather than replacing the entire array.
Yes, that's definitely a problem.  Thanks for pointing it out.  I'll try to have a look this afternoon.

**Comment by marshallward** [comment] 2016-09-20 00:40
Looks like the issue is that `patch` is basically equivalent to an update like this:

    &nml
        fib = 1, 1, 2, 3, 5
        fib = 1, 2, 3, 5
    /

It is "updating" the old vector with the new values.

The current state is currently a problem, since there's currently no way to replace a 5-element array with a 4-element array.  Maybe the right thing to do here is to simply overwrite here, but there may be use cases where one only wants to patch the first four values.

I am leaning towards just overwriting the values here, but maybe a more comprehensive solution is possible here.

**Comment by marshallward** [comment] 2016-09-20 00:48
Sorry, my last post was mistaken.  The value is overridden by the patched value.

It is skipping over the additional values, possibly as "whitespace" or "comments", which I think was the point being made in #35.  I will look a bit further.

**Comment by marshallward** [comment] 2016-09-20 12:16
I've just pushed a change (8b099a202929c17e587b16d39c6c57a80672673a) that may solve this problem.  Could you give it a try?

**Comment by marshallward** [comment] 2016-09-22 06:25
This appears to be working now so I'm going to close this ticket.

If you get around to testing it and find any problems, feel free to re-open it.

**Closed by marshallward** 2016-09-22 06:25 UTC
Labels: bug

**Comment by jpli** [comment] 2016-09-25 13:51
Just tested, looks alright now, thanks!
