### ISSUE TITLE
init Namelist from dict

### ISSUE THREAD

**Issue by gitporst** [marshallward/f90nml#60] opened 2018-01-11 14:25 UTC
I would like to generate namelists based on (nested) dictionaries. 
```
f = io.StringIO()
n = f90nml.Namelist({'sec': {'entry': [1, 2, 3]}})
n.write(f)
```
But this does not work due to non-existing start_indices. 
```
>           i_s = v_start[::-1][len(v_idx)]
E           TypeError: 'NoneType' object is not subscriptable

```
I find it also problematic, that the call to writestream() from write() is in a try-finally clause, so errors are not raised.

I did not find anything like the default_start_index property as in the Parser class for the Namelist class. What is the best way to achieve the overall goal of writing a namelist from dict?

**Comment by marshallward** [comment] 2018-01-11 20:08
I think that I have reproduced this based on your other issue #61.  But is there an error in your example?  If I run this:

    print(f.getvalue())

then I see the correct output:

    &sec
        entry = 1, 2, 3
    /

If I run the example that I put in #61, then the TypeError is raised.  So I am not sure I understand your comment about `writestream` not raising an error?

In any case, I think that these two issues are more or less the same issue, yes?

**Comment by marshallward** [comment] 2018-01-11 20:10
BTW, there was an older version with this bug.  Are you using the newest version?

**Comment by gitporst** [comment] 2018-01-12 09:22
yeah, i was originally using the older version, but the problem persisted in the newer version, also. The problem is, that in the Namelist write method, the call of self.writestream is in a try-finally clause, so all errors raised by the writestream go unnoticed.
Then in writestream, the iteration is done and in write_nmlgrp the start indices are accessed defaulting None. 
`v_start = grp_vars.start_index.get(v_name, None)` They are then passed to the var_strings method. There is no check for None for the v_start argument but in line 418 the v_start argument is directly accessed:
line 418 - `i_s = v_start[::-1][len(v_idx)]`
That is the place, where the TypeError is raised, I think.

I think a global default list index would be nice to fall back to instead of None in write_nmlgrp. Or else the var_strings method can set the default v_start or v_idx at the beginning of the method (or directly in the arglist if default is not the empty list).

**Comment by gitporst** [comment] 2018-01-12 09:37
sorry, I just realized you've already made the fixes. Thank you very much for that. They fix the TypeError and the namelist is written. Still, I am expecting
```
&sec
    entry(1:3) = 1, 2, 3
/
```
instead of
```
&sec
    entry = 1, 2, 3
/
```

**Comment by marshallward** [comment] 2018-01-12 10:04
That output is by design.  Since you created `sec` from a `dict`, there is no explicit start index.  If the module were to print `entry(1:3)` without the start index set, then it could inadvertently assign data to arrays whose start index was not 1.

If you want to get the desired output, set the start index:

    import f90nml
    d = {'sec': {'entry': [1, 2, 3]}}
    nml = f90nml.Namelist(d)
    nml['sec'].start_index['entry'] = [1]
    print(nml)

Having said that, there is a lot of room for improving control over vector output (see #24 for example).

Also, it's not terribly intuitive to manually set the `start_index`, since it was more intended as internal metadata set during parsing of a namelist.  I might be convinced to allow both vector (for mutlidimensional) and  scalar (for single-dimension vectors) input arguments.

**Comment by marshallward** [comment] 2018-01-12 10:14
Also, I still do not understand why `writestream` was not raising an error for you.  First, because omitting the `except` block should still raise the error, and second because I was still seeing the error in the case described in #61.  Can you give a code block using v0.23 which produces the bad output but does not raise the error?

Using v0.23 (not the current version), I run this:

```
import io
import f90nml
x = {'x_nml': {'a': [{'b': 1, 'c': 2}, {'b': 3, 'c': 4}]}}
f = io.StringIO()
n = f90nml.Namelist(x)
n.write(f)
```

And I get a `TypeError`:

```
Traceback (most recent call last):
  File "z.py", line 7, in <module>
    n.write(f)
  File "/home/marshall/python/f90nml/f90nml/namelist.py", line 269, in write
    self.writestream(nml_file, sort)
  File "/home/marshall/python/f90nml/f90nml/namelist.py", line 291, in writestream
    self.write_nmlgrp(grp_name, grp_vars, nml_file, sort)
  File "/home/marshall/python/f90nml/f90nml/namelist.py", line 312, in write_nmlgrp
    for v_str in self.var_strings(v_name, v_val, v_start=v_start):
  File "/home/marshall/python/f90nml/f90nml/namelist.py", line 375, in var_strings
    i_s = v_start[::-1][len(v_idx)]
TypeError: 'NoneType' object is not subscriptable
```

Can you show me the code block which does not raise this error?

**Comment by gitporst** [comment] 2018-01-15 08:07
I cannot because you are right that omitting the except statement still raises the error. I am sorry for causing the confusion (I cannot reconstruct the problem).

When converting dicts to Namelists, I would like all list entries to be handled as vectors, starting with 1. Currently I am using this to recursively alter my Namelist:

```
    def _set_start_index(nml, start_index=1):
        for k, v in nml.items():
            if isinstance(v, dict):
                v = Namelist(v)
            if isinstance(v, Namelist):
                nml[k] = _set_start_index(v, start_index)
                if not nml[k].start_index:
                    nml[k].start_index = {k1: [start_index] for k1, v1 in v.items() if isinstance(v1, list)}
            elif isinstance(v, list):
                for i, list_item in enumerate(v):
                    if isinstance(list_item, dict):
                        list_item = Namelist(list_item)
                    if isinstance(list_item, Namelist):
                        nml[k][i] = _set_start_index(list_item, start_index)
                        if not nml[k].start_index:
                            nml[k][i].start_index = {k1: [start_index] for k1, v1 in list_item.items() if isinstance(v1, list)}
        return nml
```
Maybe we could merge that into the module?

**Comment by marshallward** [comment] 2018-01-16 22:25
Yeah, I think this could be useful.

I think it could be better to define something like this within `__setitem__` however, combined with something like `default_start_index` property (set to `None` as default), since it would avoid having to call the function, as well as avoiding the deep recursive search/replace. 

The function could still be useful, but I imagine it's less likely that one would want to re-define the start index.

I have not thought much about using `Namelist` to build new namelists.  Thanks for raising these issues.

**Comment by marshallward** [comment] 2018-01-17 06:14
I've pushed a new branch [startindex](/marshallward/f90nml/tree/startindex) which introduces a property `default_start_index` and an input for the constructor which should have this feature.  Used like this:
```
import f90nml
d = {'x_nml': {'x': [1, 2, 3]}}
nml = f90nml.Namelist(d, default_start_index=1)
print(nml)
```
I may change the name of this input.

**Comment by marshallward** [comment] 2018-01-17 08:38
Sorry, seems I forgot to push these commits to GitHub... sorry about that, I will have to update this later.

**Comment by marshallward** [comment] 2018-01-17 11:25
OK, the startindex branch should be updated now.

**Comment by marshallward** [comment] 2018-01-21 23:20
I'm going to merge this into master now.  Assuming all is good, I will probably close this issue soon.  It would be good to get your feedback though before finalising the input arguments.

**Comment by marshallward** [comment] 2018-01-21 23:22
I've merged a fix into `master`, we now send a `\n` upon `StopIteration`, which should be safe since we aggressively check for `\n` to terminate iteration outside of `next`.

Thanks for spotting and reporting this, let me know how you go with it.

**Comment by marshallward** [comment] 2018-01-21 23:22
Oops wrong issue, deleting these messages...

**Comment by marshallward** [comment] 2018-01-29 00:44
This has gone through a bit of a flux (and was inadvertently broken for most of one day) but all appears good now as both a property and as an input to the constructor.

I'm going to close this issue, feel free to re-open it if you want to give additional feedback.

**Closed by marshallward** 2018-01-29 00:44 UTC
