### ISSUE TITLE
Comment char inside namelist group

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/f90nml#17] opened 2015-09-17 01:35 UTC
Not sure if this is even legal namelist syntax, but f90nml didn't like this:

```fortran
# Time stepping parameters
 &PARM03
#startTime=0,
#endTime=311040000,
#endTime=12000.0,
 deltaT=1200.0,
 ntimesteps=10,
 abEps=0.1,
 pChkptFreq=2592000.0,
 chkptFreq=120000.0,
 dumpFreq=2592000.0,
 monitorSelect=2,
 monitorFreq=1.,
 &
```

and munged it into this:
```fortran
&parm03
    starttime = 0, '#'
    endtime = 12000.0, '#'
    deltat = 1200.0
    ntimesteps = 10
    abeps = 0.1
    pchkptfreq = 12000.0
    chkptfreq = 0
    dumpfreq = 2592000.0
    monitorselect = 2
    monitorfreq = 1.0
    niter0 = 0
/
```

**Comment by marshallward** [comment] 2015-09-17 01:37
I don't know of any fortran compiler that allows # for comments.  Where is
this from?

This is solvable (just add it to the comment tokens), but I'm not sure that
it should be solved.

**Comment by marshallward** [comment] 2015-09-17 05:32
I'd almost say that it's working as intended, since it's not allowing `#` to be a variable name and is treating it as an independent token, and just slapping it onto the prior variable.

But I just tested this in gfortran, and it fails because it's looking for variables named `#startTime`. So maybe the best solution here is to add `#` to the valid fortran variable character set (even if it's non-standard). 

Even supporting this scenario is crazy, but might as well get it right.

**Comment by aidanheerdegen** [comment] 2015-09-17 05:37
Oh right, of course. He should have been using �!�, sorry, I�m was being slow ... 

I don�t think there is a right answer. I�d like to warn the user that they shouldn�t do that though.

**Comment by aidanheerdegen** [comment] 2015-09-17 05:38
Sorry, but just realised, there are �#� comment chars in the rest of the file which f90nml (and various fortran compilers) are grokking ok. Is that part of the standard?

**Comment by marshallward** [comment] 2015-09-17 05:39
grokking as in not crashing?  Is it appending them to the previous variable as before?

**Comment by marshallward** [comment] 2015-09-17 05:39
BTW I just tested adding `#` as a wordchar and it works fine (or at least matches gfortran behaviour) so I am inclined to make this change.

**Comment by aidanheerdegen** [comment] 2015-09-17 05:40
The namelist file I sent you looked like this:

```fortran

# Time stepping parameters
 &PARM03
 deltaT=1200.0,
 ntimesteps=100,
 abEps=0.1,
 pChkptFreq=2592000.0,
 chkptFreq=120000.0,
 dumpFreq=6000.0,
 monitorSelect=2,
 monitorFreq=1.,
 &

# Gridding parameters
 &PARM04
 usingCartesianGrid=.TRUE.,
 usingSphericalPolarGrid=.FALSE.,
 delX=60*20E3,
 delY=60*20E3,
 delZ=5000.,
 &
```
and f90nml was doing sensible things with the # comment chars between the groups (ignoring them mostly)

**Comment by marshallward** [comment] 2015-09-17 05:41
Fortran just ignores everything between the namelists, so that's all you are seeing.  It's just a happy coincidence that they look like scripting comments.

**Comment by aidanheerdegen** [comment] 2015-09-17 05:42
Oh right, so actually misleading. Annoying.

**Comment by marshallward** [comment] 2015-09-17 05:43
(well, almost everything, there is still the stdout/stderr markers, but no one uses those anyway)

**Comment by marshallward** [comment] 2015-09-17 10:01
More info on this:

Although gfortran treats `#startTime` as a namelist variable, it is not possible to create a variable with this name in the Fortran program (as per the standard), so this is at best inconsistent.

Intel Fortran just rejects the `#` characters altogether.

I think the answer here is to (1) parse the variables with `#` (and any other special characters) but also (2) validate the variable names.  I will raise a warning and skip the parameter - which has the added benefit of acting as a commented line :D.

I will try to write this patch tonight. 

(And none of this has to do with the original issue, which is that `#` was never gonna work anyway.)

**Comment by marshallward** [comment] 2015-09-21 09:50
I wonder if this is a old style fortran column effect? Maybe column one is indicating a comment?

**Comment by marshallward** [comment] 2015-09-22 00:46
Mystery solved, MITgcm has a custom comment scraper, see this file:

eesupp/src/open_copy_data_file.F

I think this is officially a Payu problem, so I am closing this.

**Closed by marshallward** 2015-09-22 00:46 UTC
