### ISSUE TITLE
Namelist with repeated groups doesn't convert to string

### ISSUE THREAD

**Issue by chunderbunny** [marshallward/f90nml#134] opened 2021-09-16 23:04 UTC
Trying to convert a namelist with repeated groups to a string seems to fail. If I do the following:

```
>>> import f90nml
>>> nml = f90nml.reads("""
... &foo
...  a = 1
... /
... &foo
...  b = 2
... /
... """)
>>> str(nml)
"Namelist([('foo', [Namelist([('a', 1)]), Namelist([('b', 2)])])])"
```
I was expecting `str(nml)` to return `"&foo\n    a = 1\n/\n&foo\n    b = 2\n/\n"`, as is the case when the group names do not repeat. Interestingly, if I use `nml.write('out.nml')`  the the output file is formatted correctly.

**Comment by marshallward** [comment] 2021-09-16 23:46
I am getting a string.
```
>>> import f90nml
>>> nml = f90nml.reads("""
... &foo
...  a = 1
... /
... &foo
...  b = 2
... /
... """)
>>> nml
Namelist([('foo', Namelist([('a', 1)])), ('_grp_foo_1', Namelist([('b', 2)]))])
>>> print(nml)
&foo
    a = 1
/

&foo
    b = 2
/
>>> str(nml)
'&foo\n    a = 1\n/\n\n&foo\n    b = 2\n/'
```

What is your Python and f90nml version, and what OS are you using?

**Comment by marshallward** [comment] 2021-09-16 23:49
Ah, my apologies, that was a development branch.  I do see what you are seeing.

Can you try this branch? https://github.com/marshallward/f90nml/tree/grp_repeat

This is an experimental branch which preserves the original ordering of repeated groups, although it does introduce a few (minor) incompatible changes.

Rather than try to figure out why your case is not working properly, maybe it's better to just merge the new branch.

**Comment by marshallward** [comment] 2021-09-17 00:00
I also think I can explain why your case is not working.   This is due to the odd method I introduced to distinguish a namelist from similar internal structures.

The `Namelist` object is used to represent multiple objects: namelists (as in `data.nml`), namelist groups (as in `&foo a = 1 /`) and derived types (as in `foo%a = 1 foo%b = 2`).

Although they are all rather different, they are all `dict`-like key-value entities, and so it ended up being very simple to just repurpose `Namelist` for all three.

The problem in this case is how to `print()` them.  The solution I adopted was to check if all of the entities are `Namelist` types.  If so, then I just presume that it's a namelist and print it as a file.  Otherwise, I print it explicitly as if using `repr()`.

However, in the current method of repeated groups, I store them as a list of `Namelist` objects.  Which is not a `Namelist`.  So it does not use the `Namelist` output method and just prints them in `repr()` style.

The experimental branch resolves this because I abandon the old "list of `Namelist` object" method and use internal renamed values for repeated groups.  But I am still using this very unsafe method to determine if I am a namelist.  I just get a bit more lucky.

None of this is good design, and probably needs to be handled with subclassing.  But it's not something I've really had much time to resolve.  But with enough harassment, perhaps I can find the motivation.

**Comment by chunderbunny** [comment] 2021-09-20 16:22
I can confirm that the grp_repeat branch does fix the issue, thanks for that. I'm going to have to do a minor refactor to account for the new way repeated groups are stored, I will wait until the branch is merged in before doing that though. 

Thanks!

**Comment by marshallward** [comment] 2021-09-20 16:59
I would not mind getting your feedback on the change before moving it into the main branch.  To sum it up:

* The old list of groups is replaced with the new records with the internal name `_grp_<name>_#`
* The groups can still be accessed by list, e.g. `nml[grp][1]`.
* Duplicate groups must be added with the `add_cogroup()` method, otherwise they clobber the existing values.  (And there are still probably issues with clobbering a group with existing cogroups).
* dict initialization with lists will no longer work, e.g. `Namelist({'nml': {'grp': [{'x' = 1, 'y': 2}]})`.

("Cogroup" is my own name for repeated groups.  I could find nothing in the standard which identifies namelist groups of the same name.)

I think this is a positive change, since it preserves the existing order, but I also recognize that it could be disruptive.  Unfortunately I haven't gotten much feedback on the change.

**Comment by chunderbunny** [comment] 2021-09-20 18:06
The first thing I notice is that `nml.__getitem__('foo')` returns a `Cogroup` object, but `nml.get('foo')` returns the first `Namelist` object in the `Cogroup`. This is not desirable because it means that the iterable returned by `nml.items()` will never be able to access the remaining items in the `Cogroup`.

**Comment by marshallward** [comment] 2021-09-26 14:20
Thanks, that is the sort of feedback I needed :).  Apologies for the long delay, I had an eventful week.

I believe the issue is that `Namelist` was using the `dict()` implementation of `get()`, which does not use the `Namelist()` dunder function `__getitem__`.

I've pushed a change which re-implements `get()`.  I think ought to give the desired result.

But I would not be surprised if there are problems with other functions which are using the `dict` `__getitem__`.

**Comment by chunderbunny** [comment] 2021-09-27 16:10
So with the latest version `nml.get('foo')` works as expected however iterating using `nml.items()` still has strange behavior. 

```
for key, val in nml.items(): print(key, val); print(type(val))
...
foo Namelist([('a', 1)])
<class 'f90nml.namelist.Namelist'>
_grp_foo_1 Namelist([('b', 2)])
<class 'f90nml.namelist.Namelist'>
```

My expectation here would be that the `val` associated with `key = 'foo'` would be a `Cogroup` object. Either that or the string representation of the object `_grp_foo_1` is also `'foo'`. I don't know if you can create an object that behaves exactly like a string but allows you to store multiple identical entries as dict keys.

**Comment by chunderbunny** [comment] 2021-09-27 18:56
Also an additional thought: it would be useful (although obviously not essential) if you imported `Cogroup` in the `__init__.py`.

**Comment by marshallward** [comment] 2021-09-28 02:57
I would have thought that it's better to iterate over each group individually, rather than gathering the similarly-named groups into a list.

I should say that the motivation for this patch was to preserve and return the original ordering of the groups, particularly when groups of different names were inserted inbetween groups of the same name.  If I return a list of groups, or cogroups, then I may potentially break that order.

> I don't know if you can create an object that behaves exactly like a string but allows you to store multiple identical entries as dict keys.

I think it gets to the heart of the problem.  The namelist group is identified like a hashable `dict` but the namelist is accessed serially as a list of groups, which leads to odd situations like this.

Having said that, the `_grp_foo_1` key is ugly, and was never really meant to be exposed to the user.  But now I see that iteration does expose it.

I will think on this a bit more.  I would also like to hear your thoughts if you have the time.

**Comment by chunderbunny** [comment] 2021-11-01 20:47
After a little investigation I found that the following seems to work:

```
        # Construct the cogroups based on the internal key values
        self._cogroups = set(
            k[5:].rsplit('_', 1)[0] for k in super(Namelist, self).__iter__() \
            if k.startswith('_grp_')
        )

...

    def __iter__(self):
        for k in super(Namelist, self).__iter__():
            if k.startswith('_grp_'):
                k = k[5:].rsplit('_', 1)[0]
            yield k

    def items(self):
        for k, v in super(Namelist, self).items():
            if k.startswith('_grp_'):
                k = k[5:].rsplit('_', 1)[0]
            yield k, v

    def keys(self):
        for k in super(Namelist, self).keys():
            if k.startswith('_grp_'):
                k = k[5:].rsplit('_', 1)[0]
            yield k
...

        # Gather the list of existing IDs
        hdr = '_grp_{0}_'.format(key)
        idx = [
            int(k.split(hdr)[1]) for k in super(Namelist, self).__iter__()
            if k.startswith(hdr)
        ]
...

    @property
    def keys(self):
        """Return the namelist keys in the cogroup."""
        cogrp_keys = [
            k for k in super(Namelist, self.nml).__iter__()
            if k.startswith('_grp_{}'.format(self.key))
            or k == self.key
        ]
        return cogrp_keys

```
I guess it might be worthwhile replacing `super(Namelist, self).__iter__()` with something a little less verbose.

**Comment by marshallward** [comment] 2021-11-12 22:49
Sorry for the long silence, I'm just getting through a rather stressful move.

I am starting to test these out and will hopefully get back you soon with feedback.

**Comment by marshallward** [comment] 2021-11-23 20:04
I've started to digest this implementation.  I've tested it out, and I think it works as expected.

I am on board with having the iterators return the duplicate key, despite the potential for confusion.  The proposed iteration is similar to how a Fortran program would read such a namelist (treating keys as keys, regardless of their position) while also preserving the original order.

However, this implementation does change one internal behavior of its `dict` and `OrderedDict` parent types, which is that `items()` will usually return the highly efficient "view" type (`dict_items` or `odict_items`).  Here, we are changing this behavior to return a `generator`.

I could not tell you the consequences of this, other than views are "better" than generators.  And I don't think we need to obsess too much about it.  But I would like to look into it a bit more.  There may be some simpler way to leverage and modify the `odict_items` rather than replacing it with a generator.

**Comment by marshallward** [comment] 2021-11-24 15:29
I have an implementation that creates and uses a `KeysView` and `ItemsView` from `collections.abc`, but I think that I will need to reforumulate the internal cogroup keys.

Currently, the original key is recycled as the first entry, and subsequent ones are labeled with `_grp_{key}_{n}`.  This never really made sense, but it was a bit justifiable when I was prepared to expose the internal keys.  But now that these will be fully hidden, I think it's alright to clobber the original key and to catch it when generating the list.

**Comment by marshallward** [comment] 2021-12-08 15:35
I've been trying to finalize this, but have been trying to suss out some odd behavior.  The one that is holding me back is the conversion back to `OrderedDict`.

If I replace `__iter__()` with a method that removes the internal key markers, then for `nml` (a `Namelist`) `OrderedDict(nml)` will use the transformed keys and will produce a different entity.

`OrderedDict(nml)` itself is not very useful in practice, since it will not recursively transform the interior `Namelist` values, but it does tell me that changing `__iter__()` could be problematic for other objects.  (It was `Namelist.todict()` where I first noticed this.)

At this point, I am considering changing `keys()`, `values()`, and `items()`, but leaving `__iter__()` alone.  Unless there's a better solution here - perhaps using `__new__` somehow?

**Comment by chunderbunny** [comment] 2021-12-08 16:42
> At this point, I am considering changing `keys()`, `values()`, and `items()`, but leaving `__iter__()` alone. Unless there's a better solution here.

I think this would be acceptable. From a practical point of view iterating over `keys()` is not so different from iterating over the object itself (even if it is not considered "best practice"). The difference in behaviour between `keys()` and `__iter__()` should be well documented though as this would be unexpected to most people.

**Comment by marshallward** [comment] 2022-05-03 20:47
Six months later...

I have introduced a `NmlKey` class, which is a string (`str`) which is otherwise normal but contains a `_key` field set to the internal key name.  Outside of the namelist, it will use the value as presented in the namelist.  For internal namelist operations (e.g `nml[key]`), it will use the hidden key.

This appears to resolve all of the iteration issues discussed in this issue.  It may even address the original issue raised (and shortly after derailed) by this issue.

More details are in the commit log.

Given how long it took to get back, I am not expecting a reply, but wanted to follow up to at least update the issue.  Assuming nothing comes up, I will merge this into the main branch.

**Comment by marshallward** [comment] 2022-05-14 12:51
This now works, even if not quite for the reason that it ought to work.  (There is still the awkward "Am I a list?" test to distinguish between namelists, groups, and derived types).  But the issue has been resolved for now so I will close this.

**Closed by marshallward** 2022-05-14 12:51 UTC
