### ISSUE TITLE
Problem writing out read-in lists in version 1.4.2

### ISSUE THREAD

**Issue by rhfogh** [marshallward/f90nml#143] opened 2022-06-14 15:42 UTC
If you read in a data structure, put part of it in a Python dictionary, and write out the dictionary with f90nml, you get an error under version 1.4.2, whereas it works fine under 1.3.1:

AttributeError: 'Cogroup' object has no attribute 'items'

The input file and test file are attached ('.txt' suffix added). Running under the two different versions, you get:

|~> python nmltest.py
f90nml: 1.3.1
Python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53) 
[GCC 9.4.0]
Done 1
[Namelist([('seg_x_axis', [1.0, 0.0, 0.0]), ('seg_y_axis', [0.0, 1.0, 0.0]), ('seg_coord', 0.0)]), Namelist([('seg_x_axis', [1.0, 0.0, 0.0]), ('seg_y_axis', [0.0, 1.0, 0.0]), ('seg_coord', 0.0)])]
Done 2

|~>  python nmltest.py
f90nml: 1.4.2
Python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53) 
[GCC 9.4.0]
Done 1
[Namelist([('seg_x_axis', [1.0, 0.0, 0.0]), ('seg_y_axis', [0.0, 1.0, 0.0]), ('seg_coord', 0.0)]), Namelist([('seg_x_axis', [1.0, 0.0, 0.0]), ('seg_y_axis', [0.0, 1.0, 0.0]), ('seg_coord', 0.0)])]
Traceback (most recent call last):
  File "nmltest.py", line 13, in <module>
    f90nml.write(result, open("testout.nml", "w"))
  File "/alt/rhfogh/Software/miniconda3/envs/mxcubeweb/lib/python3.7/site-packages/f90nml/__init__.py", line 82, in write
    nml_in.write(nml_path, force=force, sort=sort)
  File "/alt/rhfogh/Software/miniconda3/envs/mxcubeweb/lib/python3.7/site-packages/f90nml/namelist.py", line 578, in write
    self._writestream(nml_file, sort)
  File "/alt/rhfogh/Software/miniconda3/envs/mxcubeweb/lib/python3.7/site-packages/f90nml/namelist.py", line 677, in _writestream
    self._write_nmlgrp(grp_name, grp_vars, nml_file, sort)
  File "/alt/rhfogh/Software/miniconda3/envs/mxcubeweb/lib/python3.7/site-packages/f90nml/namelist.py", line 693, in _write_nmlgrp
    for v_name, v_val in grp_vars.items():
AttributeError: 'Cogroup' object has no attribute 'items'

[nmltest.py.txt](https://github.com/marshallward/f90nml/files/8901316/nmltest.py.txt)
[testin.nml.txt](https://github.com/marshallward/f90nml/files/8901317/testin.nml.txt)

Still sticking with version 1.3.1

**Comment by marshallward** [comment] 2022-06-14 17:29
Thanks for continuing to report these issues.  I can reproduce this.

The namlist -> dict -> namelist conversion has led to the `segments` key being assigned to the `Cogroup` (a `list` subclass), which should not happen.  The constructor needs to catch these and re-key them to internal values.

In v1.3.1, it was safe to assume that any list (or `Cogroup`) was a list of namelist groups with the same name, and were handled appropriately.  But this was always a flawed assumption (outlined in various prior issues) and I think the new approach is the correct one.

Unfortunately, I still do not have a clear vision for how to initialize a namelist with duplicate groups.  This issue is a reflection of that problem.

This particular problem is perhaps easier, since the `Cogroup` contains enough metadata to reconstruct the namelist.  But if it were a `list`, then I don't know if it would be possible.

I will try to resolve this soon.

**Comment by marshallward** [comment] 2022-06-16 20:07
@rhfogh If you have the time, can you test this branch? https://github.com/marshallward/f90nml/tree/cogroup_input

**Comment by marshallward** [comment] 2022-06-21 00:03
Going to assume that this fixes your issues (although perhaps I've scared off any future 1.4.x users).

Feel free to reopen if it's a problem.

**Closed by marshallward** 2022-06-21 00:03 UTC

**Comment by rhfogh** [comment] 2022-06-21 07:25
Sorry, It has been an extremely busy week. Thanks for the fix.
