### ISSUE TITLE
patching a repeated section on a namelist returns an unclear message

### ISSUE THREAD

**Issue by mandresm** [marshallward/f90nml#150] opened 2022-11-09 17:28 UTC
Related to esm-tools/esm_tools#843

# Problem description

When loading a namelist with repeated sections, and then I try to `patch` one or several repeated sections, I get the following error:
```
AttributeError: 'Cogroup' object has no attribute 'update'
```

I understand it is not possible to update repeated sections, as it is not clear which one f90nml should patch. However, I find the error message misleading.

# Example

To reproduce the error you can write the following `fort.4` namelist:
```
&NAMDIM
    NPROMA = -8, 
/

&NAMPAR0
    LSTATS = true,
    LDETAILED_STATS = false,
    LSYNCSTATS = false,
    MP_TYPE = 2,
    MBX_SIZE = 32000000,
    NPROC = 144,      ! Number of MPI ranks (cores of no OpenMP)
    NOUTPUT = 1,
/

&NAEPHY
    LEPHYS = true,
    LERADI = true,
    LELAIV = false,
/

&NAERAD
    NRPROMA = -8, 
    CRTABLEDIR = "./rtables/",  ! Modify this for your installation, note trailing /
/

&NAMPAR0
/
&NAEPHY
/
&NAERAD
/
```

Then you can use the following python3 script to reproduce the error:
```python
import f90nml

nml = f90nml.read("fort.4")

changes = { 
    "namdim": {
        "nproma": 0
    }   
}

nml.patch(changes)

print(nml)
print("Changing variables in non-repeated sections works!")
print()
print("Here comes the problem:")

changes = { 
    "nampar0": {
        "lstats": False
    },  
    "naephy": {
        "leradi": False
    },
    "naerad": {
        "nrproma": 0
    },
}

nml.patch(changes)
```

# Suggested solution

Ideally, the user should be reported which variables are problematic in this context. I have sketched a very rough solution with the desired behaviour for these lines:
https://github.com/marshallward/f90nml/blob/2a8663aa7dfc06a446fbab6aae20d928f694f3fb/f90nml/namelist.py#L649-L658

The rough solution:
```diff
    def patch(self, nml_patch):
        """Update the namelist from another partial or full namelist.

        This is different from the intrinsic `update()` method, which replaces
        a namelist section.  Rather, it updates the values within a section.
        """
+       conflicting_repeated_secs = [] 
        for sec in nml_patch:
            if sec not in self:
                self[sec] = Namelist()
-           self[sec].update(nml_patch[sec])
+           try: 
+               self[sec].update(nml_patch[sec])
+           except AttributeError:
+               conflicting_repeated_secs.append(sec)
+       if conflicting_repeated_secs:
+           raise AttributeError(
+               "The following sections are repeated in the namelist and cannot be "
+               f"updated: {conflicting_repeated_secs}"
+           )  
```

**Comment by marshallward** [comment] 2022-11-10 12:44
I can reproduce this.  This is due to the recent "Cogroup" support for repeated namelist groups.

Thanks for reporting this, I will look over your proposed solution.

**Comment by seb-wahl** [comment] 2023-07-12 08:07
I'm hitting the same problem as @mandresm. For me it would be of great help in our workflow if f90nml patches the variable in ALL repeated namelists. Sticking with the example above (if you add an `print(xml)` to @mandresm  example script) the patched namelist would look like
```
&namdim
    nproma = 0
/

&nampar0
    lstats = .false.
    ldetailed_stats = .false.
    lsyncstats = .false.
    mp_type = 2
    mbx_size = 32000000
    nproc = 144
    noutput = 1
/

&naephy
    lephys = .true.
    leradi = .false.
    lelaiv = .false.
/

&naerad
    nrproma = 0
    crtabledir = './rtables/'
/

&nampar0
    lstats = .false.
/

&naephy
    leradi = .false.
/

&naerad
    nrproma = 0
/
```
I know this is not an ideal behavior (and should print a warning to the user) but it will allow me to continue to use f90nml in my current project. 
This behavior can be achieved by modifying the code section @mandresm posted above by:
```python
   def patch(self, nml_patch):
        """Update the namelist from another partial or full namelist.

        This is different from the intrinsic `update()` method, which replaces
        a namelist section.  Rather, it updates the values within a section.
        """
        for sec in nml_patch:
            if sec not in self:
                self[sec] = Namelist()
            if isinstance(self[sec],Cogroup):
                for nml_dict in self[sec]:
                    nml_dict.update(nml_patch[sec])
            else:
                self[sec].update(nml_patch[sec])
```

**Comment by marshallward** [comment] 2023-07-12 18:25
This solution seems fine for now, can you please submit it as a PR?

It would be ideal to implement this in Cogroup, but my few attempts did not work well.  Until this, this seems reasonable.

**Comment by marshallward** [comment] 2023-07-12 18:35
Actually I seem to have fallen upon a solution.

I have a question.  Each group is repeated here (ie they are "cogroups").  Should each one be patched?  The first?  The last?  Or should there be some syntax to control which ones are patched?

The implementation that I've written up currently patches all of them.

**Comment by marshallward** [comment] 2023-07-12 19:48
A test branch is available here:

https://github.com/marshallward/f90nml/tree/cogroup_update

**Comment by seb-wahl** [comment] 2023-07-13 07:10
Hi
the solution in the test branch works for me. Ideally I would like to be able to control at some point which namelist I would like to update, but I have no idea how to achieve this as they don't have an identifier except for a running number, right?
Is it an ordered dict i.e. the first of the duplicate namelists always get assigned `1`, the second one `2`, ... 
A suggestion would be to use a comment as an identifier but (without having looked at the code in detail) I believe is difficult to realize:
```
&test ! hi
  var1 = 'hi out there'
  var2 = 2
/
&test ! another repetition
  var1 = "it's summer"
  var3 = 'a different variable'
/
```
and then the strings `'hi'` and `'another repetition'` will be used to identify the repeated section.
This is not super urgent, as I can continue with the current solution from the https://github.com/marshallward/f90nml/tree/cogroup_update branch

**Comment by mandresm** [comment] 2023-07-13 08:47
Hi both,

It also works for me. However, I am not sure this is the solution that we really need:

We are using climate models that use non-standard namelists in which sections are repeated, and each of these repeated section is interpreted by the model as a different entity by itself: there are some special variables (e.g. `filetag`) within the special named sections (e.g. `&mvstreamctl`) that the model use to "understand" that is a different entity:
```
&mvstreamctl
    filetag = 'co2'
    source = 'co2'
/

&mvstreamctl
    filetag = 'surf'
    source = 'surf'
/
``` 

Patching both is not a solution for us, because they are different entities for our models, but also I see that this is a non-standard way of using the namelists, so I am wondering whether f90nml really needs to solve our problem and our very specific desired behavior: editing the variables in these repeated lists independently. Maybe we can handle it ourselves, in any case @marshallward your advice on tackling this problem is very much welcome, since you know what could we use from f90nml to wrap a solution for our case.

I like the idea of @seb-wahl of having them be differentiated by comments. @marshallward, is there a way of extracting the comments that are near the section title?

**Comment by mandresm** [comment] 2023-07-13 09:11
Hi @seb-wahl, I see, then that's really good news that this is already working :)

I'm still wondering though, if the comments are attributes of the Namelist objects. What I have in mind is in the lines of the following example:
```
print(nml["output_nml"|.get_comment())
```

This might deserve it's own issue though...

**Comment by marshallward** [comment] 2023-07-13 18:03
The Cogroups are lists, and the index should match the ordering in the namelist file.

You can still individually update the contents, e.g.:
```
nml['nampar0'][0]['lstats'] = False
```
So using `update()` is more of a convenience function.

I could add an argument to `update()` which selects the element.  We would be deviating from the existing `dict` API, but I suppose that is not a big deal here.  The default to be to patch all of them, or it could simply be a required argument.

(Using inline comments is probably not going to work, partly because of the namelist whitespace rules, and partly the f90nml parser does not even attempt to read them.)

**Comment by marshallward** [comment] 2023-07-13 18:07
Another option is to indicate the cogroup index with metadata, e.g.
```
changes = {
    "nampar0": {
        "lstats": False
        "_index": 0
    },
    "naephy": {
        "leradi": False
        "_index": -1
    },
    "naerad": {
        "nrproma": 0
    },
}
```
This would patch the first instance of `nampar0`, the last instance of `naephy` and all instances of `naerad`.

**Comment by marshallward** [comment] 2023-08-14 20:22
I feel like we're very close to a solution here.  It would be good to close out the issue and do a new release.

From reading the comments:

1. `patch()` is a new operation with no real precedent in existing types like `dict()`, so we have signficant latitude on how to handle this.

2. Applying the patch to all of the elements in the Cogroup is potentially disruptive, although perhaps it makes sense as a default operation.

3. Extracting index from underscored metadata in the patch is an option.  (Extracting from comments is currently not possible, and may not even work in the most general of cases.)

Given these facts, I am inclined to do something such as shown in the previous comment.  If there's no objection then I will probably push this change soon.

Thanks to both of you for your patience; it's not easy for me to devote time to these smaller projects.

**Comment by mandresm** [comment] 2023-08-15 05:07
Apologies, I have not read your proposed solution until now (I guess we all struggle with devoting time to small projects :) ).

The solution you are proposing with the `_index` will definitely help us immensely and it's definitely a better way of achieving the desired behavior in comparison with the comment solution we were proposing.

Thanks for your work and efforts @marshallward!

**Comment by marshallward** [comment] 2023-08-23 15:07
Thanks for your incredible patience, @mandresm.  I have updated the `cogroup_update` to support the `_index` argument which selects the member of the cogroup.  It seems to do what I proposed above, but I'll give you a chance to review it.

**Comment by mandresm** [comment] 2023-08-24 07:19
Thanks a lot @marshallward, I'll have a look and test it. I should have time for that tomorrow.

**Comment by marshallward** [comment] 2023-10-11 02:09
I think this is working now, so I'm going to close the issue.  I'll do a release soon (v1.4.4)

**Closed by marshallward** 2023-10-11 02:09 UTC
