### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by greyltc** [marshallward/f90nml#43] opened 2017-03-10 00:17 UTC
`f90nml.read()` crashes when reading a file with the following namelist which I *think* is valid:

```
&parameter name=dnux/dp, symbol="$gx$r$bx$n", units="1/(2$gp$r)", description="Horizontal chromaticity", type=double, &end
```

I'm expecting:
```
Namelist([('parameter',
           Namelist([('name', 'dnux/dp'),
                     ('symbol', '$gx$r$bx$n'),
                     ('units', '1/(2$gp$r)'),
                     ('description', 'Horizontal chromaticity'),
                     ('type', 'double')]))])
```

I guess the `/` in the `name` field is tripping up your state machine.

**Comment by marshallward** [comment] 2017-03-13 11:07
Thanks for reporting this.  Sorry for not replying, I'm still in the middle of my monthlong holiday and don't always have easy access to a computer.

I won't be in a position to look into this more until I get back, but the problem is again similar #42.  Isuspect that I need to take greater care with whitespace between tokens in variable names.  Hopefully you can use string delimiters in the meantime.

**Comment by marshallward** [comment] 2017-03-13 12:52
For what it's worth, I just tested out strings with slashes in gfortran and Intel fortran:

1. gfortran rejects the namelist if there are no delimiters around the string.
2. Intel fortran does not require delimiters, but terminates the namelist after the '/'

But I'm guessing that the namelists appear valid in your runs.  Which compiler are you using?

As for this bug, my guess is that `f90ml` interprets `&parameter name=dnux /` as the first namelist, ignores everything else upto `&end`, which starts a new namelist, and then fails because this "new" namelist is never closed.

**Comment by greyltc** [comment] 2017-03-13 17:01
The short answer to "Which compiler are you using?" is "I'm not using any."

The long answer is

I'm using your `f90nml` in my project, [python-sdds](https://github.com/greyltc/python-sdds), to help me decode the header region of the [SDDS (Self Describing Data Set) file format](http://www.aps.anl.gov/Accelerator_Systems_Division/Accelerator_Operations_Physics/manuals/SDDStoolkit/SDDStoolkit.html). The [documentation there](http://www.aps.anl.gov/Accelerator_Systems_Division/Accelerator_Operations_Physics/manuals/SDDStoolkit/SDDStoolkitsu2.html#x5-40002.2) calls the header region "namelist-like constructs" and I don't actually know what version of FORTRAN it's based on. It's entirely possible that the namelist-like things I'm trying to parse with your project here don't conform to any FORTRAN standard. I might just lucky enough that the SSDS headers are close enough to proper FORTRAN namelists that your code works almost all the time for me and with [minor overrides](https://github.com/greyltc/python-sdds/blob/master/sdds/SDDS.py#L113-L146). I'm not familiar enough with FORTRAN namelist standards to read the SDDS header definition and immediately know where they diverge though.

I've been testing my sdds parser on various input files I can get my hands on and I've found that some of them have / in the names. The SDDS standard document even explicitly says

> Names may contain any alphanumeric character, as well as any of the following: @ : # + - % . _ $ & / . The first letter of a name may not be a digit.

**Comment by marshallward** [comment] 2017-04-28 01:25
Closing this one, for the same reason as #42.  Again, feel free to re-open if progress can be made on those points.

**Comment by marshallward** [comment] 2017-04-28 01:28
Actually, I gues the point of these tickets (#42, #43) is that SDDS should be regarded as a format that is similar, but not identical to, Fortran namelists, and f90nml could potentially be adapted to support SDDS with a little extra work.  Maybe adoption of some sort of control flag could help make some progress here.

I'll open a new ticket addressing that issue, and tag it as a future feature.

**Comment by marshallward** [comment] 2017-04-28 01:32
Easier just to re-open, and explicitly tag as an SDDS issue.

**Comment by marshallward** [comment] 2019-06-12 13:17
I think SDDS support is unlikely to ever happen without some major user-driven feedback, since it relies on a lot of tokens which cause severe problems in standard namelist parsing, in both `f90nml` and in standard Fortran programs.

Closing for now, happy to reopen if the need is urgent though.

**Closed by marshallward** 2019-06-12 13:17 UTC
Labels: sdds
