### ISSUE TITLE
encoding f90str('string with a backslash \\')

### ISSUE THREAD

**Issue by sound-fx** [marshallward/f90nml#22] opened 2016-02-18 00:03 UTC
Thank you for publishing f90nml.  I'm using v0.17.

In the Namelist class (f90nml/namelist.py), the definition for self.f90str should accommodate character strings with backslash characters.  Something like:

```
            str:
                lambda x: repr(x).replace("\\'", "''").replace('\\"', '""').replace('\\\\', '\\'),
```

instead of

```
            str:
                lambda x: repr(x).replace("\\'", "''").replace('\\"', '""'),
```

To be sure, the definition should also accommodate still other characters that Python escapes, including \a, \b, \f, \n, \r, \t, and \v, but I'm not sufficiently familiar with fortran namelists to know how to correctly encode these.

**Comment by marshallward** [comment] 2016-02-18 04:49
Thanks very much for this (and I received your patch).  I confirmed the problem, and the slashes appear properly resolved now. 

As for the other escape characters, I think the best thing to do might be to keep your patch as-is, which preserves the escape characters into the namelist string.

Best I can tell, Fortran doesn't properly support escape characters.  But most compilers provide some way to interpret them, and it all should work fine as written in the namelist file.

This is the first time I've ever manually added a patch (`git am`) but it looks like it was successfuly added (e0baaab406f794b17f03e0f9250c788063168cb1).

Thanks again for the patch!

**Comment by marshallward** [comment] 2016-02-27 00:41
Assuming this is all good now, closing this.

**Closed by marshallward** 2016-02-27 00:41 UTC

**Comment by jacobwilliams** [comment] 2016-03-17 04:40
Was just about to submit a ticket for this same issue, but then noticed you had already fixed it. Any idea when it will make it into a PyPi release?

**Comment by marshallward** [comment] 2016-03-17 04:47
Sure, I need to document the whole file object imput thing, after that I'll do a release (maybe today??)

**Comment by marshallward** [comment] 2016-03-17 06:02
PyPI should be updated now.
