### ISSUE TITLE
Add a dependency on the yaml module

### ISSUE THREAD

**Issue by zbeekman** [marshallward/f90nml#96] opened 2019-06-03 21:47 UTC
Trying to use `f90nml` after installing on macOS via `pip3 install f90nml` with the `-f yaml` flag results in: 

```
f90nml: error: YAML module could not be found.
```

I think you should just add an explicit dependency on `pyyaml`. Or, better yet, if there's a way to add a recommended (installed by default) dependency on `pyyaml` that someone could opt out of. (I'm not familiar enough with python packaging to know for certain if this is possible one way or the other.)

**Comment by zbeekman** [comment] 2019-06-03 21:48
Relates to https://github.com/openjournals/joss-reviews/issues/1474

**Comment by zbeekman** [comment] 2019-06-03 21:48
You could always just provide a `requirements.txt` at the top level that provides it.

**Comment by marshallward** [comment] 2019-06-04 14:28
I'd prefer to not add it as a dependency, since there is a design goal to only use standard library dependencies (hence no `requirements.txt` file).  So the error is sort of intentional.

It's not a lot of trouble to optionally install it though, e.g. `requests` has a `requests[security]` install.  I could similarly do a `f90nml[yaml]` install.

**Comment by zbeekman** [comment] 2019-06-04 17:28
> I'd prefer to not add it as a dependency, since there is a design goal to only use standard library dependencies (hence no `requirements.txt` file). So the error is sort of intentional.
> 
> It's not a lot of trouble to optionally install it though, e.g. `requests` has a `requests[security]` install. I could similarly do a `f90nml[yaml]` install.

All of that sounds good. Basically, it would be nice to have better documentation when:

1. You request yaml output but the module isn't present, and
2. You won't be able to use the yaml capabilities w/o installing the module

Documentation & error handling would be sufficient, IMO, to resolve this.

**Comment by marshallward** [comment] 2019-06-05 12:15
Reminding myself to include a message to install PyYAML in the error, as recommended by @zbeekman

**Comment by rgieseke** [comment] 2019-06-05 12:45
Not sure if that's necessary here, but this is how Pandas handles its conditional imports and warnings:

https://github.com/pandas-dev/pandas/blob/master/pandas/io/html.py#L29

https://github.com/pandas-dev/pandas/blob/master/pandas/io/html.py#L833

Maybe something simpler also works for `f90nml`.

**Comment by marshallward** [comment] 2019-06-05 12:59
Thanks @rgieseke, I'd say that I'm currently doing something similar (`try`-`except ImportError`).  Interestingly, there is no reference to those libs as optional dependencies in Pandas' `setup.py`.

I'm currently trying out an optional dependency at the moment, `pip install -e . [yaml]`, along with a message explaining this in the command line.  But maybe I'm just overthinking the whole thing and should just make it a dependency :).

**Comment by rgieseke** [comment] 2019-06-05 13:25
Yeah, i think the Pandas workflow is that you just have to install them yourself. The docs list them as optional dependencies: https://pandas.pydata.org/pandas-docs/stable/install.html

Not having them as a dependency would save some install time (which can add up in CI) and most likely not all people need the yaml support.

So maybe the optional [yaml] install is a good compromise.

**Comment by marshallward** [comment] 2019-06-10 14:37
I've pushed some changes which add a `f90nml[yaml]` install, additional instructions for installing the YAML support, and added this information to the error message when YAML is unavailable.

Assuming that all looks good, I'll probably close this issue.

**Comment by zbeekman** [comment] 2019-06-10 15:41
It looks good, but, for me, adding `-e` causes pip installation to fail. I can do `--user` without `-e` and things seem fine. That is independent of with or without yaml.

**Comment by zbeekman** [comment] 2019-06-10 15:42
FYI, I haven't tried within a venv, I'm just doing global installs like a madman.

**Comment by marshallward** [comment] 2019-06-10 15:45
What is the error you're seeing?  I am still not 100% clear on when the `-e` flag is appropriate.

**Comment by zbeekman** [comment] 2019-06-10 15:51
It looks like you need to pass a path to the `-e` flag.

```
$ pip3 install -e --user .[yaml]
--user should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+
```

Adding `.` after the `-e` flag seems to have resolved it.

From the help:
```
  -e, --editable <path/url>   Install a project in editable mode (i.e. setuptools "develop mode") from a local project path or a VCS url.
```

I don't think it's required at all for users. I would get rid of it. (But I might be wrong.)

**Comment by zbeekman** [comment] 2019-06-10 15:58
Interesting, if I do:

```
$ pip3 install -e .[yaml] --user
Obtaining file:///Users/ibeekman/Sandbox/f90nml
Requirement already satisfied: PyYAML in /usr/local/lib/python3.7/site-packages (from f90nml==1.1.1) (5.1)
Installing collected packages: f90nml
  Running setup.py develop for f90nml
Successfully installed f90nml
```

That seems to work fine. But the output is different than if I do:
```
$ Processing /Users/ibeekman/Sandbox/f90nml
Requirement already satisfied: PyYAML in /Users/ibeekman/Library/Python/3.7/lib/python/site-packages (from f90nml==1.1.1) (5.1.1)
Building wheels for collected packages: f90nml
  Building wheel for f90nml (setup.py) ... done
  Stored in directory: /private/var/folders/d0/9mds_bmn77j80rnyw0btcz0r0000gq/T/tmp/tmp/tmp/tmp/tmp/tmp/tmp/pip-ephem-wheel-cache-pp5r2_vn/wheels/a0/02/5d/8edb3e17962104c646d68b7e5ad387cde9e11efb61399a44c1
Successfully built f90nml
Installing collected packages: f90nml
Successfully installed f90nml-1.1.1
```

I think users would want the wheel to be built and should use the version without `-e`. (I'm no python expert, though...)

**Comment by marshallward** [comment] 2019-06-10 17:39
I think you've worked it out, I mixed up the `--user` and `-e` flags.  It's not even possible to use `--user` in virtualenv, so I think you've tested it in the correct way :).  (Certainly better than I did!)

I think `pip install --user -e .` is probably the way to go here, I'll test it out and make sure it's all working this time.  I'll swap those and update it ASAP.

**Comment by marshallward** [comment] 2019-06-10 17:41
Committed here `11224c0c5334fd540e10a895ca90cbc196c0defc`

**Comment by zbeekman** [comment] 2019-06-10 17:58
I think you should drop the `-e` flag, but it should work with or without it. With `-e` it won't build and install a wheel, so it may be slightly slower...

**Comment by marshallward** [comment] 2019-06-12 12:40
Agreed, just had a bit of a test and `-e` does not actually install the package anyway; just create a meta-package that links to your directory, which is probably not the expected behavior.

I've updated the README and removed the flags, and will do a PyPI update now.

**Comment by marshallward** [comment] 2019-06-13 12:54
Sounds like this may all be sorted out, so I will close this issue for now.

**Closed by marshallward** 2019-06-13 12:54 UTC
